server:
  port: 9763

spring:
  application:
    name: yxx-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            # 允许跨域
            allowed-origins: "*"
            allowed-methods:
            - GET
            - POST
            - PUT
            - DELETE
            allowed-headers: "*"
            allow-credentials: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
      - StripPrefix=2
      # 熔断器 服务down机时进入熔断器，服务异常不进入
      - name: Hystrix
        args:
          # HystrixCommand
          name: fallbackcmd
          fallback-uri: forward:/defaultfallback
      # 重试机制
      - name: Retry
        args:
          # 重试次数
          retries: 3
          statuses: BAD_GATEWAY,GATEWAY_TIMEOUT,SERVICE_UNAVAILABLE,INTERNAL_SERVER_ERROR
          series:
          - SERVER_ERROR
          methods:
          - GET
          - POST
          exceptions:
          - java.io.IOException
          - org.springframework.cloud.gateway.support.TimeoutException
      routes:
      # 服务a
      - id: api-message
        uri: lb://yxx-message
        predicates:
        - Path=/api/msg/**
      # 服务b
      - id: api-streaming
        uri: lb://yxx-streaming
        predicates:
        - Path=/api/stream/**
      # 服务b
      - id: api-elastic
        uri: lb://yxx-elastic
        predicates:
        - Path=/api/elastic/**
      # 服务b
      - id: api-chat
        uri: lb://yxx-chat
        predicates:
        - Path=/api/chat/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9761/eureka/
  instance:
    prefer-ip-address: true
