server:
    port: 9766

spring:
    application:
        name: yxx-elastic

    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest

    cloud:
        #开启配置服务发现
        config:
            fail-fast: true
            discovery:
                enabled: true
                service-id: yxx-config
            name: common
#      label: master
#      profile: @profileActive@
#      uri: @env.config.url@
#      username: @env.username@
#      password: @env.password@

eureka:
    client:
        service-url:
            defaultZone: http://localhost:9761/eureka/
    instance:
        prefer-ip-address: true

elastic:
    job:
        cron: 0/5 * * * * ?
        shardingTotalCount: 2
        shardingItemParameters: 0=Chengdu0,1=Chengdu1
        zk:
            serverList: 127.0.0.1:2181
            namespace: cxytiandi_job2
