server:
    port: 9761

eureka:
    instance:
        hostname: localhost
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://localhost:9761/eureka/
    server:
        enable-self-preservation: false

spring:
    application:
        name: eurka-server
