server:
  port: 9764

spring:
  application:
    name: yxx-message

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    #开启配置服务发现
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: yxx-config
      name: common
#      label: master
#      profile: @profileActive@
#      uri: @env.config.url@
#      username: @env.username@
#      password: @env.password@

# Ribbon
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000

# Feign
feign:
  compression:
    request:
      # 开启请求压缩功能
      enabled: true
      # 指定压缩请求数据类型
      mime-types: text/xml;application/xml;application/json
      #如果传输超过该字节，就对其进行压缩
      min-request-size: 2048
    response:
      # 开启响应压缩功能
      enabled: true
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 30000
        loggerLevel: basic

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9761/eureka/
  instance:
    prefer-ip-address: true
